.husky/pre-commit
.prettierrc
package.json
src/constant/type.ts
src/pages/_app.tsx
src/pages/_document.tsx
src/pages/api/hello.ts
src/pages/index.tsx

5월 1일 회의를 통해 정해진 type interface를 작성하였습니다.
추가로 develop 브랜치에 적용되어있지 않은  husky , prettier세팅을 추가하는 PR입니다.

type interface 선언

---

package-lock.json
package.json
src/pages/_app.tsx
src/styles/GlobalStyle.tsx

reset css 적용후
모든 요소의 boxsizing을 border-box로 설정했습니다

[#18]feature: styled-reset모듈 reset css 적용

---

package-lock.json
src/assets/icons/index.ts
src/assets/social/index.ts
src/components/common/Header.tsx
src/styles/icons.ts

asset/index.ts 에서 default export 로 경로 매핑을 해주어 해결했습니다.
이후 svg가 추가될때마다 해당 작업 해주시면 될 것 같습니다~

Test/svg import 빌드 시 SVG 절대경로 매핑 문제 해결

---

package-lock.json
src/components/modal/NoticeModal.tsx
src/pages/design.tsx

[#16] fix: build error 수정

---

src/pages/design.tsx

해당 PR 머지하면 빌드 잘 될 것 같습니다~
깃헙에서 중복되는 파일을 강제로 파일 삭제하면서 대소문자 변경이 자동으로 안이뤄졌던 문제였어요.

[#16] fix: 파일 경로 대소문자 수정

---

src/pages/design.tsx

컬러 부분 비교할 때 어떤 색인지 매칭이 조금 어려워 위와 같이 수정했습니다

style: color 확인하는 부분 수정

---

src/assets/Indicators.tsx
src/components/list/index.tsx
src/components/list/styles.tsx
src/pages/list/index.tsx

- 대소문자에 문제가 있던 부분들 (Indecators 액박, 경로 ) 수정하였습니다.
- 경로 변경에 따른 Spinner Animation이 멈추던 부분을 해결하였습니다.
- 추가로 리스트 페이지에서 새로고침 하면 순간적으로 NotFound 가 보여지는 문제가 있다는 걸 알게 되었습니다. 리스트 페이지에서의 검색 공백 처리 문제로 인해 발생한 이슈였기에 이후 Search Input 에서 공백 검색을 처리하도록 수정하는게 좋아보인다고 판단하여 해당 처리 부분을 제거하였습니다.

Hotfix/build error 대소문자 변경, 스피너 애니메이션 수정

---

next.config.js

```
images: {
unoptimized: true,
},
```
공식홈페이지를 참고하여 추가하였습니다.

[#62] fix: next.config.js image unoptimized 추가

---

src/components/SearchInput.tsx
src/pages/index.tsx
src/pages/savingamount/index.tsx
src/styles/font.ts

| main |  amount |
|--------|--------|
| ![image](https://github.com/SobiSa-Expense-Hunter/SobiSa/assets/108770949/482dda27-fe06-474b-9b8c-e2d14453d433) | ![image](https://github.com/SobiSa-Expense-Hunter/SobiSa/assets/108770949/f0314125-51f8-453d-b1fe-20eee4a82eb7) |

Feature/ios input zoom & ux writing & font style guide에 맞지 않게 되어있던 부분 수정

---

src/components/common/Modal.ts
src/components/modal/ChoseProductModal.tsx
src/components/modal/NoticeModal.tsx

- 모달에 폰트 적용
- 제품명이 모달창에서 모두 확인할 수 있도록 수정

[#69] feature: 모달 폰트 적용 및 제품명이 모두 보이게 수정

---

src/assets/Icons.tsx
src/components/SearchInput.tsx
src/components/common/Header.tsx
src/components/layout/AppLayout.tsx
src/components/list/index.tsx
src/components/modal/CertificateAndShareModal.tsx
src/components/results/Alternative.tsx
src/components/results/index.tsx
src/pages/index.tsx
src/pages/result.tsx
src/pages/savingamount/index.tsx
src/styles/GlobalStyle.tsx

f2e564ca91f9f2311505021e343c772edf37b561  : 배경 적용만 한 커밋
66284b7dc1db2f87198cba8d1632a3dd1df9a2f8 : 배경 적용에 따른 이슈 해결한 커밋
| f2e564ca91f9f2311505021e343c772edf37b561 | 66284b7dc1db2f87198cba8d1632a3dd1df9a2f8|
|--------|--------|
| ![image](https://github.com/SobiSa-Expense-Hunter/SobiSa/assets/108770949/80d19675-0b79-4e1b-a2c4-9fc6314d60dd) | ![image](https://github.com/SobiSa-Expense-Hunter/SobiSa/assets/108770949/436b4693-8410-42d6-af7d-efc3beac6b4c)|
AppLayout에서 header를 전역 너비를 설정하는 컴포넌트 안에 넣었습니다.
(강남언니 사이트를 참고하여  헤더를 안쪽으로 넣었습니다.)
전역 값을 조절하다보니 마지막 result page의 AlternativeWrapper의 폭이 길어지는 현상이 있었는데,
AlternativeWrapper의 min-width를 추가하니 해결되었습니다.
제가 확인했을때는 다른 css 문제될건 못봤지만,
판다님쪽 코드를 만지기도 했고 전역 레이아웃을 건드려서.. 확인 한번 부탁드려요~!

Feature/header layout 배경 적용에 따른 레이아웃 구조 수정

---

src/components/modal/CertificateAndShareModal.tsx
src/components/results/Certificate.tsx

[수정사항]
- offscreenCanvas 추가
- 임명장 텍스트 로고 스티커 애니메이션 삭제
- 300-> 500 ms로 추가

[#58] fix: IOS 환경에서 임명장 이미지 다운로드 오류

---

src/pages/about/index.tsx
src/pages/index.tsx

로컬스토리지를 이용해 초기 진입 체크
방문 기록이 없으면 about page로 이동

[#80] fix: 초기 진입 체크 및 about page 하던 버튼 라우팅 수정

---

src/components/list/index.tsx

- window 객체로 구현하던 scrollTo 수정
- overFlow된 scroll을 담당하던 컴포넌트를 ref 객체로 연결하여 구현

[#85] fix: list page top 버튼 기능 복구

---

src/components/modal/CertificateAndShareModal.tsx

[요약]
- offscreenCanvas  및 setTimeout 제거
[세부사항]
- offscreenCanvas를 worker 없이 사용할 시 해당 코드에서 얻는 이익이 없을 것 같아 제거하였습니다. (지원하지 않는 브라우저 버전도 있구요.)
- requestAnimationFrame를 재귀적으로 호출하고 있어 setTimeout을 주는 부분이 불필요하다 여겨져 이를 수정하였습니다.
(맥북 사파리에서 잘 동작함을 확인하였습니다.)

[#58] fix: 필요로 하지 않는 소스 제거

---

src/pages/_document.tsx

[#90] fix: meta tag 오타 수정

---

src/lib/gtag.ts
src/pages/_app.tsx
src/pages/_document.tsx

- GA, Clarty 적용 완료
-  잘 적용이 되었는지 확인하기 위해 버셀 연결된 레포에서 브랜치 생성해서 작업
- **GA 스크린샷** 
(버튼 이벤트 집계 함수는 구현만해두고 적용하진 않았어요)
- **Clarity 스크린샷**
이후 추가적으로 어떤 버튼에 이벤트 함수를 넣을지 상의가 필요할 것 같아요.

Feature/#96 ga-clarity 적용

---

src/components/SearchInput.tsx

- 문자가 공백(space) 밖에 없으면 검색이 되지 않게 처리 -> 반복되는 router.push, try,catch 로직 유틸함수로 분리
- 진입 시 searchInput 에 auto focus 추가 -> ref 를 이용해 구현

Bug/#102 searchInput 공백 예외 처리 및 자동 포커스 기능 추가

---

src/components/results/Certificate.tsx

[수정사항]
word-break: keep-all; 이 ''로 인해 정상적으로 작동하지 않아 이를 수정

[#112] [Bug] 임명장 글자 줄바꿈 문제

---

src/assets/Images.tsx

MainImage width, height 기본값 추가

hotfix: build-error 수정

---

src/__test__/dummy/UserSelectData.ts
src/components/common/Modal.ts
src/components/common/share/KakaoButton.tsx
src/components/common/share/NativeShareButton.tsx
src/components/results/CertificateAndShareModal.tsx
src/components/results/ShareButtons.tsx
src/pages/_app.tsx
src/pages/index.tsx
src/types/kakaoSDK.ts
src/types/result.ts

- navigator.canshare()로 함수 안에 공유할 인수를 넣지 않으면 지원하는 브라우저도 false로 값을 보이고 있음
- canshare 인수로 공유할 메세지를 넘겨주어 실제 공유할 메세지가 공유가 되는지 여부를 판단하도록 수정

[#109] [Bug] 결과 공유 페이지에 navigator.share 버튼이 보이지 않는 현상

---

src/components/results/Certificate.tsx

- 임명장 시간 표기를 지키면서 현재 시간을 나타내도록 수정
- 시간은 0 -23 시 표기

[Bug] 임명장 시간 표기 오류

---

src/components/SearchProvider.tsx

실제로 저장되어야 할 값이 dispatch로 store의 값이 변경된 후여야 함
dispatch로 변경 후의 값이 return 되지 않으며, store 의 값이 변경되어 다시 리렌더링 되어 useEffect로 처리

[#116] useEffect를 이용해 dispatch 후 값을 sessionStorage로 저장하도록 함

---

public/naver7624eea371d02a5aa8049900a0cc29bf.html

[#128] [Feature] naver search advisor html 업로드

---

public/google6a7f85ba2fedf174.html

google search advisor html 업로드

[#128] [Feature] google search advisor html 업로드

---

src/components/common/share/NativeShareButton.tsx
src/components/results/ShareButtons.tsx
src/constant/index.ts

NativeShareButton에 기존 설명 문구만 공유되고 있어, title, description, url을 공유하는 api 공유 포맷에 맞게 수정

[#126] [Bug] Native Share Button공유 메시지 변경

---

src/components/event/Card.tsx

[#134] fix: 태그 아래 본문 여백 추가

---

src/pages/_app.tsx
src/pages/_document.tsx

_documnetd의 `<header>` 가 아닌 _app 컴포넌트로 ga, cliarity 코드를 이동하였습니다.
수집 연결이 되는건지 develop에서 한번 확인하고 가는게 좋을것같아요

[#139] fix: GA tag 위치 _app.tsx 로 수정

---

src/components/SearchInput.tsx
src/components/common/Header.tsx
src/components/common/Modal.ts
src/components/layout/AppLayout.tsx
src/components/list/styles.ts
src/pages/savingamount/index.tsx

- 레이아웃에서 height 고정을 list 페이지에만 적용하도록 수정
- header margin-top에서 padding-top으로 변경하여 본문 내용이 헤더 침범하여 보이는 현상 수정

[#142, #144] feature: 레이아웃에서 height 고정 변경 및, header margin-top에서 padding-top으로 변경

---

src/components/results/CertificateAndShareModal.tsx

원래 이미지 크기보다 크기를 2배로 그리게 하여 더 많은 픽셀이 그려질 수 있도록 구현

[#148] [Feature] 임명장 이미지 화질 개선

---

src/pages/list/index.tsx

- 추가 검색 및 url 자체 수정 시 인식 기능 복구
- list 접근 유효성 검사를 담당하는 useEffect에 의존성 배열 추가 및 router 가 준비되었을때만 실행하도록 변경
https://github.com/SobiSa-Expense-Hunter/SobiSa/assets/108770949/22684b43-60ed-4dc8-8549-f4c0665b0745

list page url params 인식 오류 수정

---

src/components/results/Alternative.tsx

애니메이션 아이템 크기를 100개로 고정하여 뻑이 나오는 현상을 수정

[feature] 기회비용 이모티콘 최대 100개 나오도록 수정

---

src/components/common/SearchInput/index.tsx

- Search Input에서 autofocus 담당하던 부분의 코드 삭제
- 시연 영상

[#184] fix: SearchInput Auto focus 삭제
